name: Build AMI with Packer

on:
  push:
    branches:
      - main

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 30 seconds
        run: sleep 30
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          zip -r Yash_Bhatia_002791499_03.zip .
      - name: Upload ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: Yash_Bhatia_002791499_03.zip

      - name: Download ZIP file
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: Yash_Bhatia_002791499_03.zip

      - name: Build AMI
        run: |
          packer init ./packer/ami.us-east-1.pkr.hcl
          packer fmt ./packer/ami.us-east-1.pkr.hcl
          packer validate ./packer/ami.us-east-1.pkr.hcl
          packer build ./packer/ami.us-east-1.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

 

 

 